server:
  port: 8084
#  servlet:
#    context-path: /ms-instructor
    
  error:
    include-details: always

# Base de datos    
# Oracle settings
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1522:orades
    username: MS022021_INSTRUCTORES
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver

# Dependencias   
    
    
    
# Observabilidad(Logs y trasas)



# Seguridad 

